name = biofuel
author = Lokrates
description = A Minetest Mod to produce biofuel from unused plants.
min_minetest_version = 5.4
depends =
optional_depends = default, mcl_core, hades_core, fl_ores, fl_core, fl_glass, pipeworks, hopper, wine, cucina_vegana, farming, basic_materials
version = 0.10
title = Biofuel
